---
functional:
  - требование 1
  - требование 2
  
  - Регистрация
  - Авторизация
  - Создание игры
  - Рейтинг

Codebattle: игра для программистов
Поэтому мы запустили Codebattle. Это игра для программистов.
Идея очень простая: вам и сопернику дается задача, вы решаете ее на выбранном вами языке. Вы видите код соперника в реальном времени, результаты запуска тестов и можете общаться с ним и зрителями в чате. Кто первый решит задачу (удовлетворит тестам) — тот победил.
Сейчас доступны на выбор JavaScript, PHP, Python и Ruby. Можно создавать игру самому и ждать соперника (или послать ссылку кому-нибудь конкретному), а можно вступать в открытые игры. В запущенную игру можно зайти в качестве зрителя. Чтобы следить за открытыми играми без посещения сайта, можно установить расширение для Chrome.
Если интересно, мы можем отдельно рассказать про бэкэнд. Там используется Erlang, а тесты пишутся на Clojure. Потом они трансформируются в тесты на всех целевых языках с помощью нашей библиотеки multicode.
Сами задачи тоже лежат на Гитхабе, можно делать пулл-реквесты и добавлять новые задачи (заодно попрактиковаться с Clojure).

  
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы.
  - Сайт должен быть безопасным и защищать данные пользователя.
  - Сайт должен быть удобным на мобильном устройстве.
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров.
  - Сайт должен быть способен обрабатывать большое количество трафика, а именно 1000 одновременных пользователей.
implicit:
  - требование 5
  - требование 6


1ый проект:

---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову.
  - Пользователь должен иметь возможность искать товары по категории.
  - Пользователь должен иметь возможность фильтровать товары по цене.
  - Пользователь должен иметь возможность фильтровать товары по цвету.
  - Пользователь должен иметь возможность фильтровать товары по наличию.
  - Пользователь должен иметь возможность фильтровать товары по бренду.
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре.
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины.
implicit:
  - Пользователь должен иметь возможность осуществлять навигацию по страницам каталога.
  - Сайт должен иметь версии на английском и русском языках.
