---
functional:
  - Есть возможность создать игру c ботом
  - Есть возможность создать игру c другим игроком
  - Есть возможность создать игру c другом
  - Есть возможность создать игру c конкретным человеком, отправив ему ссылку
  - Есть возможность вступать в открытые игры
  - В запущенную игру можно зайти в качестве зрителя
  - В одно и то же время можно участвовать только в одной игре
  - Задачу можно решать на английском или русском языках
  - Есть возможность видеть код соперника в реальном времени
  - Есть возможность видеть результаты запуска тестов в реальном времени
  - Есть возможность общаться с соперником и зрителями в чате 
  - Победа определяется тем, кто первый решит задачу, т.е. удовлетворит тестам
  - Игра завершается проигрышем, если выбрать опцию "Сдаться"
  - В игре есть гайд по прохождению игры
  - В игре есть возможность сбросить код до первоначального вида
  - В игре есть возможность просмотреть историю игры
  - Есть возможность поделиться историей игры
  - В игре есть возможность заново начать игру с тем же противником и параметрами
  - Для игры доступны языки на выбор JavaScript, PHP, Python и Ruby 
  - На сайте есть рейтинг игроков
  - Можно установить расширение для Chrome, чтобы следить за открытыми играми без посещения сайта
  - Пользователь должен иметь возможность зарегистрироваться
  - Пользователь должен иметь возможность авторизоваться по емейлу
  - При неправильном емейле пользователь должен получить сообщение об ошибке
  - При неправильном пароле пользователь должен получить сообщение об ошибке
  - Пользователь должен иметь возможность авторизоваться через профиль в Github
  - Пользователь должен иметь возможность авторизоваться через профиль в Discord
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика, а именно 1000 одновременных пользователей
implicit:
  - Пользователю не должно быть доступно окно для отправлений сообщений в чате на канале Notification, предназначенном для системных сообщений
  - Емейл пользователя должен быть подтвержден при регистрации
