---
functional:
  - Есть возможность создать игру самому, ждать соперника или послать ссылку кому-нибудь конкретному
  - Есть возможность вступать в открытые игры
  - В запущенную игру можно зайти в качестве зрителя
  - Задачу можно решать на английском или русском языках
  - Есть возможность видеть код соперника в реальном времени
  - Есть возможность видеть результаты запуска тестов в реальном времени
  - Есть возможность общаться с соперником и зрителями в чате 
  - Победа определяется тем, кто первый решит задачу, т.е. удовлетворит тестам
  - Для игры доступны языки на выбор JavaScript, PHP, Python и Ruby 
  - Можно установить расширение для Chrome, чтобы следить за открытыми играми без посещения сайта
  - Пользователь должен иметь возможность зарегистрироваться
 
  - Пользователь должен иметь возможность авторизоваться по емейлу
  - Пользователь должен иметь возможность авторизоваться через профиль в Github
  - На сайте есть рейтинг игроков
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика, а именно 1000 одновременных пользователей
implicit:
  - Емейл пользователя должен пройти валидацию при регистрации 
  - Пользователю не должен быть доступно окно для отправлений сообщений в чате Notifications, предназначенном для системных сообщений  
